name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *"  # roda a cada 5 minutos
  workflow_dispatch:       # também permite rodar manualmente

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request to keep app awake
        run: curl -s https://vasta-calculator-a-b-test.onrender.com/
